### Creates the IT Department
POST http://localhost:8080/departments
Content-Type: application/json

{
    "name": "IT Apartment"
}

### Creates the Marketing Department
POST http://localhost:8080/departments
Content-Type: application/json

{
    "name": "Marketing Department"
}

### Creates the HR Department
POST http://localhost:8080/departments
Content-Type: application/json

{
    "name": "HR Department"
}

### Creates the TEST Department
POST http://localhost:8080/departments
Content-Type: application/json

{
    "name": "TEST Department"
}

### List all departments
GET http://localhost:8080/departments



### Get department with ID 1
GET http://localhost:8080/departments/1

### Get department with ID 2
GET http://localhost:8080/departments/2

### Get department with ID 3
GET http://localhost:8080/departments/3


### Get department with ID 4
GET http://localhost:8080/departments/4


### Update department with ID 1. Fixes typo
PUT http://localhost:8080/departments/1
Content-Type: application/json
{
    "name": "IT Department"
}




### Delete department with ID 4
DELETE http://localhost:8080/departments/4
