POST http://localhost:8080/users
content-type: application/json

# {
#     "name": "test",
#     "username": "test",
#     "password": "test"
# }

{
"name": "Marco Villasmil",
"username": "marcoandresv",
"password": "123456"
}



GET http://localhost:8080/users
Accept: application/json


