###
@H="http://localhost:8080"

###
@token="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcyMDIxNjAzMiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS9sb2dpbiIsInJvbGVzIjpbIkFETUlOIl19.2x0oymVEn-VUa2tzDl5DGXOnitPjP_3__gbm9cvxfqg"


###########################################################



### Login admin user
POST {{H}}/api/login
accept: application/json

{
   "username": "admin",
    "password": "admin"
}


### Login default user
POST {{H}}/api/login
accept: application/json

{
   "username": "miguel",
    "password": "password"
}


###########################################################

### Creates a new task
POST {{H}}/tasks
Content-Type: application/json
authorization: {{token}}

{
    "title": "Setup worker computers",
    "description": "Need to set up worker computers for our office",
    "status": "IN_PROGRESS",
    "departmentId": 1,
    "createdById": 2,
    "assignedUserIds": [1, 2]
}

### Creates a task by user with ID 2
POST {{H}}/tasks
Content-Type: application/json
authorization: {{token}}


{
  "title": "Interview new candidates",
  "description": "Interview loop scheduling and preparation",
  "dueDate": "2024-07-01T00:00:00",
  "priority": "MEDIUM",
  "status": "NOT_STARTED",
  "departmentId": 3,
  "createdById": 3,
  "assignedUserIds": [6]
}

### Creates a task for the Test department
POST {{H}}/tasks
Content-Type: application/json
authorization: {{token}}


{
  "title": "TEST TASK",
  "description": "NEW TEST",
  "dueDate": "2024-07-01T00:00:00",
  "priority": "LOW",
  "status": "NOT_STARTED",
  "departmentId": 1,
  "createdById": 2
}

### Creates another task
POST {{H}}/tasks
Content-Type: application/json
authorization: {{token}}


{
  "title": "Work on budget for next week",
  "description": "Need to work on budget for next week",
  "dueDate": "2024-07-15T00:00:00",
  "priority": "HIGH",
  "status": "NOT_STARTED",
  "departmentId": 1,
  "createdById": 4,
  "assignedUserIds": [3, 4]
}

### Creates another task
POST {{H}}/tasks
Content-Type: application/json
authorization: {{token}}


{
  "title": "new task",
  "description": "fresh out the oven",
  "priority": "LOW",
  "status": "NOT_STARTED",
  "departmentId": 3,
  "createdById": 3,
  "assignedUserIds": [3, 4]
}

### Get all tasks
GET {{H}}/tasks
authorization: {{token}}


### Gets task with task ID 1
GET {{H}}/tasks/1
authorization: {{token}}

### Gets task with task ID 2
GET {{H}}/tasks/2
authorization: {{token}}

### Updates task with task ID 5
PUT {{H}}/tasks/5
Content-Type: application/json
authorization: {{token}}

{
    "title": "Old task",
    "description": "this is an old task",
    "status": "COMPLETED"
}


### Gets tasks created by user with ID 1
GET {{H}}/tasks/created-by/1
Accept: application/json
authorization: {{token}}



### Gets tasks assigned to user with ID 2
GET {{H}}/tasks/assigned-to/2
Accept: application/json
authorization: {{token}}


### Delete task with ID 2
DELETE {{H}}/tasks/2
authorization: {{token}}

### Delete task with ID 4
DELETE {{H}}/tasks/4
authorization: {{token}}
