###
@H="http://localhost:8080"

###
@token="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxOTc3OTMxOCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS9sb2dpbiIsInJvbGVzIjpbIkFETUlOIl19.oNrMJtwj6TJIRP1D4yEAZrUJddOWuCTP3a_UbhWID5k"




###
### Login admin user
POST {{H}}/api/login
accept: application/json

{
   "username": "admin",
    "password": "admin"
}


###
### Login marco 
POST {{H}}/api/login
accept: application/json

{
   "username": "marcoandresv",
    "password": "123456"
}


### Post a user
POST {{H}}/users
content-type: application/json
Authorization: {{token}}

{
    "name": "Marco Villasmil",
    "username": "marcoandresv",
    "password": "123456",
    "role": "ADMIN"
}

### Post another user
POST {{H}}/users
content-type: application/json
Authorization: {{token}}


{
    "name": "Julie",
    "username": "djou",
    "password": "test",
    "role": "USER"
}

### Post Test user
POST {{H}}/users
content-type: application/json
Authorization: {{token}}

{
    "name": "TEST test",
    "username": "test",
    "password": "test",
    "role": "USER"
}

### Post another user
POST {{H}}/users
content-type: application/json
Authorization: {{token}}


{
    "name": "supeeertessssttt",
    "username": "qwerwerewr",
    "password": "asdlfkashgl",
    "role": "USER"
}


### Get all users
GET {{H}}/users
content-type: application/json
authorization: {{token}}


### Get user with ID 1
GET {{H}}/users/1
authorization: {{token}}

### Get user with ID 2
GET {{H}}/users/2
authorization: {{token}}

### Get user with ID 3
GET {{H}}/users/3
authorization: {{token}}

### Get user with an invalid ID
GET {{H}}/users/555
authorization: {{token}}


### Get user with username "marcoandresv"
GET {{H}}/users/username/marcoandresv
authorization: {{token}}

### Get user with username "djou"
GET {{H}}/users/username/djou
authorization: {{token}}

### Get user with username "test"
GET {{H}}/users/username/test
authorization: {{token}}

### tries to get a fake user
GET {{H}}/users/username/doesnotexist
authorization: {{token}}


### Update user with ID 2
PUT {{H}}/users/2
content-type: application/json
authorization: {{token}}


{
    "name": "Marco Andres",
    "username": "marcoandresv",
    "password": "marco",
    "departmentId": 4
}

#### Deletes user with ID 3
DELETE {{H}}/users/3
authorization: {{token}}

#### Deletes user with ID 4
DELETE {{H}}/users/4
authorization: {{token}}

#### Deletes user with ID 6
DELETE {{H}}/users/6
authorization: {{token}}


