

POST http://localhost:8080/users
content-type: application/json
{
    "name": "Marco Villasmil",
    "username": "marcoandresv",
    "password": "123456"
}

POST http://localhost:8080/users
content-type: application/json
{
    "name": "Julie",
    "username": "djou",
    "password": "test"
}

POST http://localhost:8080/users
content-type: application/json
{
    "name": "TEST test",
    "username": "test",
    "password": "test"
}



GET http://localhost:8080/users
Accept: application/json


GET http://localhost:8080/users/1
GET http://localhost:8080/users/2
GET http://localhost:8080/users/3
GET http://localhost:8080/users/555


GET http://localhost:8080/users/username/marcoandresv

GET http://localhost:8080/users/username/djou

GET http://localhost:8080/users/username/test

GET http://localhost:8080/users/username/doesnotexist


PUT http://localhost:8080/users/1
content-type: application/json
{
    "name": "Marco Andres",
    "username": "marcoandresv",
    "password": "marco"
}


DELETE http://localhost:8080/users/3

DELETE http://localhost:8080/users/4

DELETE http://localhost:8080/users/5


