###
@H="http://localhost:8080"

###
@token="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtaWd1ZWwiLCJleHAiOjE3MjAyMDQ2NzYsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9hcGkvbG9naW4iLCJyb2xlcyI6WyJVU0VSIl19.-f7MEn7PsUAB1fcTt00YkZiKWVE93fEhL7c9Jb1Aqtw"


###########################################################



### Login admin user
POST {{H}}/api/login
accept: application/json

{
   "username": "admin",
    "password": "admin"
}


###
### Login ADMIN user
POST {{H}}/api/login
accept: application/json

{
   "username": "marcoandresv",
    "password": "123456"
}



### Login default user
POST {{H}}/api/login
accept: application/json

{
   "username": "miguel",
    "password": "password"
}

###########################################################

### Post a user
POST {{H}}/users
content-type: application/json
Authorization: {{token}}

{
    "name": "Marco Villasmil",
    "username": "marcoandresv",
    "password": "123456",
    "role": "ADMIN"
}

### Post another user
POST {{H}}/users
content-type: application/json
Authorization: {{token}}


{
    "name": "Lisa Medina",
    "username": "lisamedinag",
    "password": "123456",
    "role": "ADMIN"
}

### Post Test user
POST {{H}}/users
content-type: application/json
Authorization: {{token}}

{
    "name": "Miguel Angel",
    "username": "miguel",
    "password": "password",
    "role": "USER"
}

### Post another user
POST {{H}}/users
content-type: application/json
Authorization: {{token}}


{
    "name": "Laura Sandu",
    "username": "laurasandu",
    "password": "123456",
    "role": "USER"
}

### Post another user
POST {{H}}/users
content-type: application/json
Authorization: {{token}}


{
    "name": "Cheyenne",
    "username": "cheyenne",
    "password": "123456",
    "role": "USER"
}

### Post another user
POST {{H}}/users
content-type: application/json
Authorization: {{token}}


{
    "name": "Lourdes Castellet",
    "username": "lourdescastellet",
    "password": "123456",
    "role": "USER"
}

### Post another user
POST {{H}}/users
content-type: application/json
Authorization: {{token}}


{
    "name": "Fake User",
    "username": "faaaaaake",
    "password": "123456",
    "role": "USER"
}


###########################################################

### GET ALL USERS
GET {{H}}/users
content-type: application/json
authorization: {{token}}


### Get user with ID 1
GET {{H}}/users/1
authorization: {{token}}

### Get user with ID 2
GET {{H}}/users/2
authorization: {{token}}

### Get user with ID 3
GET {{H}}/users/3
authorization: {{token}}

### Get user with an invalid ID
GET {{H}}/users/555
authorization: {{token}}


### Get user with username "marcoandresv" 
GET {{H}}/users/username/marcoandresv
authorization: {{token}}

### Get user with username 
GET {{H}}/users/username/cheyenne
authorization: {{token}}

### Get user with username "test"
GET {{H}}/users/username/lisamedinag
authorization: {{token}}

### tries to get a fake user
GET {{H}}/users/username/doesnotexist
authorization: {{token}}


###########################################################

### Update user with ID 2
PUT {{H}}/users/2
content-type: application/json
authorization: {{token}}


{
    "name": "Marco Andres",
    "username": "marcoandresv",
    "password": "marco",
    "departmentId": 4
}

###########################################################

#### Deletes user with ID
DELETE {{H}}/users/3
authorization: {{token}}

#### Deletes user with ID 
DELETE {{H}}/users/4
authorization: {{token}}

#### Deletes user with ID
DELETE {{H}}/users/8
authorization: {{token}}


